trackmoney/options/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("test/", views.test_options, name="test_options"),
    path("test-options/", views.Options.as_view()),
]

trackmoney/shares/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("", views.ShareProcess.as_view(), name="shares-add" ),
    path("list", views.ShareListView.as_view(), name="shares-list" ),
]

trackmoney/trackmoney/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("options/", include("options.urls")),
    path("shares/", include("shares.urls") ),
]

trackmoney/options/models.py
from django.db import models

# Create your models here.

trackmoney/shares/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.http import request

# Create your models here.

txn_types = [("Buy", "Buy"),
            ("Sell", "Sell"),
            ("Div", "Div")
            ]

class Share(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    symbol = models.CharField(max_length=30)
    company_name = models.CharField(max_length=100)
    tnx_type = models.CharField(max_length=5, choices=txn_types)
    quantity = models.FloatField()
    txn_price = models.FloatField()
    txn_date = models.DateField()
    last_updated = models.DateTimeField(default=timezone.now)

trackmoney/shares/forms.py
from django.forms import ModelForm
from shares.models import Share

class ShareForm(ModelForm):
    class Meta:
        model = Share
        fields = ["symbol", "company_name", "tnx_type", "quantity", "txn_price", "txn_date"]

trackmoney/options/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View

# Create your views here.

def test_options(request):
    return HttpResponse("Thsi is your first page")

class Options(View):
    message = "This is first message"
    template_name = "options/index.html"
    def get(self, request, *args, **kwargs):
        print(args)
        return render(request, self.template_name, {})

trackmoney/shares/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from .forms import ShareForm
from django.views.generic import ListView
from .models import Share
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Sum


# Create your views here.

def index(request):
    return HttpResponse("This is test")


class ShareProcess(View):
    template_name = "shares/share_process.html"
    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        form = ShareForm()
        return render(request, self.template_name, {"form": form})

    @method_decorator(login_required)
    def post(self, request,  *args, **kwargs):
        form = ShareForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.owner = request.user
            obj.save()
            return render(request, "shares/share_list.html", {"share_list": Share.objects.filter(owner=self.request.user)})
        else:
            return render(request, self.template_name, {"form": form, "error": "some problem with form"})

@method_decorator(login_required, name="dispatch")        
class ShareListView(ListView):
    context_object_name = "share_list"
    template_name = "shares/share_list.html"

    def get_queryset(self):
        user = self.request.user
        return Share.objects.filter(owner=user).aggregate(Sum('txn_price'))

trackmoney/options/templates/options/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="theme-light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link  rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
</head>
<body>
    <h1>This is the first page from template</h1>
    <div class="columns">
        <div class="column is-6">
            <div id="chart"></div>
        </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    <script src="{% static 'options/js/draw_chart.js' %}"></script>
</body>
</html>

trackmoney/shares/templates/shares/share_list.html
{% extends "shares/base.html" %}
    
{% block body %}

</ul>
<div class="columns mt-6">
    <div class="column is-8 is-offset-2 is-10-mobile is-offset-1-mobile">
        <a href="/shares"><button class="button is-primary is-outlined is-small" >Add Transaction</button></a>
    </div>
</div>
<div class="columns">
    <div class="column is-8 is-offset-2 is-10-mobile is-offset-1-mobile">
        <div class="columns is-multiline">
            {% for share in share_list %}
                <div class="column is-4">
                    <div class="card">
                        <div class="card-content">
                        <div class="content">

                            <div class="columns is-mobile">
                                <div class="column">
                                    <div class="cell is-size-6 has-text-weight-bold">{{share.symbol}}</div>
                                </div>
                                <div class="column">
                                    {% if share.symbol == "TCS.NS" %}
                                    <div class="cell is-size-6 has-text-weight-bold has-text-danger-on-scheme">{{share.txn_price}}(-18%)</div>
                                    {% else %}
                                    <div class="cell is-size-6 has-text-weight-bold has-text-success-on-scheme">{{share.txn_price}}(+18%)</div>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="columns is-mobile">
                                <div class="column">
                                    <div class="cell is-size-7 has-text-weight-semibold">Avg 456.64</div>
                                </div>
                                <div class="column">
                                    <div class="cell is-size-7 has-text-weight-semibold">LTP 538.85</div>
                                </div>
                            </div>
                            <div class="columns is-mobile">
                                <div class="column">
                                    <div class="cell is-size-6 has-text-weight-semibold">Invested 1000</div>
                                </div>
                                <div class="column">
                                    <div class="cell is-size-6 has-text-weight-semibold">Current 1050</div>
                                </div>
                            </div>

                            <div class="columns is-mobile">
                                <div class="column is-3 is-offset-5">
                                    <button class="button is-primary is-outlined is-small ml-5" >Transaction List</button>
                                </div>
                            </div>
                            
                        </div>
                        </div>
                    </div>
                </div>
            {% endfor %}   
        </div>
    </div>
</div>






{% endblock %}

trackmoney/shares/templates/shares/share_process.html
{% extends "shares/base.html" %}
    
{% block body %}
<div class="mt-5">
    <form method="post">
        {% csrf_token %}
        
        <label for="{{ form.symbol.id_for_label }}">Symbol</label>
        {{ form.symbol}}
        <label for="{{ form.company_name.id_for_label }}">Company Name</label>
        {{ form.company_name}}
        <label for="{{ form.tnx_type.id_for_label }}">Transaction Type</label>
        {{ form.tnx_type}}
        <label for="{{ form.quantity.id_for_label }}">Quantity</label>
        {{ form.quantity}}
        <label for="{{ form.txn_price.id_for_label }}">Transaction Price</label>
        {{ form.txn_price}}
        <label for="{{ form.txn_date.id_for_label }}">Transaction Date</label>
        <input type="date" name="txn_date" required="" id="id_txn_date" value="{{form.txn_date.value}}">
        <button>Submit</button>
    </form>
</div>
{% endblock %}